version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=2021-mnts
  backend-app:
    image: alvaniev/2021-mnts-backend
    container_name: 2021-mnts-backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_DBDIALECT=mysql
      - NODE_DBHOST=db
      - NODE_DBPORT=3306
      - NODE_DBUSER=root
      - NODE_DBPWD=root
      - NODE_DBSCHEMA=2021-mnts
      - NODE_DBSYNC=true
      - NODE_HOST=http://192.168.56.3:3000
